# Generated by Django 2.2.12 on 2020-05-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssgenerator', '0007_items_nullOrEmptyLink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date published'),
        ),
    ]
