# Generated by Django 2.2.13 on 2020-08-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rssgenerator', '0008_modelPubDate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sid', models.CharField(max_length=256, unique=True)),
            ],
        ),
    ]
